
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      # - back:/app +1
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    networks:
      - nginx-php-mysql81

  frontend:
    build: ./frontend
    volumes:
      # - front:/app 
      - './frontend:/app'
      # - '/app/node_modules' - тупо лишнее. В самом конте он висит. И с ПРАВИЛЬНЫМ портом
    ports:
      - 8080:8080
    networks:
      - nginx-php-mysql81

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    container_name: ac_an_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "account_analitic_db"
    # volumes:
    #   - dbData:/var/lib/mysql
    networks:
      - nginx-php-mysql81

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_account_analitic
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=account_analitic_db
    restart: always
    ports:
      - 8081:80
    networks:
      - nginx-php-mysql81

  # nginx-service:
  #   image: nginx:stable-alpine
  #   container_name: nginx-container_acc_an
  #   ports:
  #       - "8180:80"
  #   # volumes:
  #   #     - ./evalarlab_dev:/var/www/html
  #   #     - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - mysql
  #   # extra_hosts:
  #   #   - "localhost:8081:127.0.0.1"
  #   hostname: localhost:8081
  #   domainname: localhost:8081
  #   networks:
  #     - nginx-php-mysql81

volumes:
  front:
  back:
networks:
  nginx-php-mysql81:
